version: "3.2"
services:
    youcomic-server:
        container_name: youcomic-server-instance
        build:
            context: .
        ports:
            - "8880:8880"
        volumes: 
            - ./conf-boot:/home/app/conf-boot
            - ./static:/home/app/static